# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Wojciech Polak
#
# Generated by scripts/render-homebrew-formula.sh in wojciechpolak/dproxy and
# rewritten in full by that repository's release workflow. Edit the renderer,
# not this file.

class Dproxy < Formula
  desc "Discreet HTTPS and WebSocket proxy over ECH-protected WSS with end-to-end TLS"
  homepage "https://github.com/wojciechpolak/dproxy"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/wojciechpolak/dproxy/releases/download/v1.0.0/dproxy_v1.0.0_darwin_arm64.tar.gz"
      sha256 "3c1787ffbc199121abc9dad9ea91c61de0d18d44e9f53c5e59f756c7e173e2b4"
    end

    on_intel do
      url "https://github.com/wojciechpolak/dproxy/releases/download/v1.0.0/dproxy_v1.0.0_darwin_amd64.tar.gz"
      sha256 "b137ddd2fb692319a43e1abacf4462e74d33f683cdd9359d8d04fcd4983c2a05"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wojciechpolak/dproxy/releases/download/v1.0.0/dproxy_v1.0.0_linux_arm64.tar.gz"
      sha256 "e46dc15bfec54c97040d0d24fcfb4b45f1d9feb1713d82e1fe8582b3aa5eb606"
    end

    on_intel do
      url "https://github.com/wojciechpolak/dproxy/releases/download/v1.0.0/dproxy_v1.0.0_linux_amd64.tar.gz"
      sha256 "61340cf6989f779174dc2ce13b414f82c5af4abca8ed4313de9401f5682907ec"
    end
  end

  def install
    bin.install "dproxy"
  end

  def caveats
    <<~EOS
      Configure the local client and token before starting the service:
        ~/.config/dproxy/client.toml
        ~/.config/dproxy/token

      Start the per-user service without sudo:
        brew services start dproxy

      Service logs are written to:
        #{var}/log/dproxy.log
    EOS
  end

  service do
    run [opt_bin/"dproxy", "client"]
    keep_alive true
    error_log_path var/"log/dproxy.log"
    stop_timeout 35
  end

  test do
    assert_match "dproxy v#{version}", shell_output("#{bin}/dproxy --version")
    output = shell_output("#{bin}/dproxy test 2>&1", 2)
    assert_match "the relay URL is required", output
  end
end
